from __future__ import annotations

STOCK_BAR_COLUMNS = [
    "date",
    "code",
    "open",
    "high",
    "low",
    "close",
    "prev_close",
    "volume",
    "amount",
    "turnover_rate",
    "is_st",
    "is_paused",
    "limit_up",
    "limit_down",
    "industry_code",
    "industry_name",
]

SECTOR_BAR_COLUMNS = [
    "date",
    "sector_code",
    "sector_name",
    "open",
    "high",
    "low",
    "close",
    "prev_close",
    "volume",
    "amount",
    "advancers_count",
    "decliners_count",
    "limit_up_count",
    "limit_down_count",
    "member_count",
]

MARKET_BAR_COLUMNS = [
    "date",
    "all_a_equal_weight_open",
    "all_a_equal_weight_high",
    "all_a_equal_weight_low",
    "all_a_equal_weight_close",
    "total_amount",
    "total_volume",
    "advancers_count",
    "decliners_count",
    "limit_up_count",
    "limit_down_count",
    "new_high_count_20",
    "new_low_count_20",
    "new_high_count_60",
    "new_low_count_60",
    "strong_stock_ratio",
    "weak_stock_ratio",
    "median_ret_pct",
]
