create table if not exists vpa_features (
    date varchar not null,
    scope_type varchar not null,
    scope_id varchar not null,
    window_n integer not null,
    open double,
    high double,
    low double,
    close double,
    prev_close double,
    volume double,
    amount double,
    ret_pct double,
    range_pct double,
    body_pct double,
    upper_shadow_pct double,
    lower_shadow_pct double,
    body_ratio double,
    upper_shadow_ratio double,
    lower_shadow_ratio double,
    close_position double,
    vol_ma_n double,
    vol_rvol_n double,
    range_pct_ma_n double,
    range_rvol_n double,
    body_pct_ma_n double,
    body_rvol_n double,
    price_high_n double,
    price_low_n double,
    prev_price_high_n double,
    prev_price_low_n double,
    price_position_n double,
    ma_n double,
    ma_slope_n double,
    primary key (date, scope_type, scope_id, window_n)
);

alter table vpa_features add column if not exists prev_price_high_n double;
alter table vpa_features add column if not exists prev_price_low_n double;

create table if not exists vpa_trend_context (
    date varchar not null,
    scope_type varchar not null,
    scope_id varchar not null,
    window_n integer not null,
    parent_window_n integer,
    parent_high double,
    parent_low double,
    parent_price_position double,
    parent_ma double,
    parent_ma_slope double,
    trend_label varchar,
    position_label varchar,
    trend_strength_score double,
    primary key (date, scope_type, scope_id, window_n)
);

create table if not exists vpa_bar_context_labels (
    date varchar not null,
    scope_type varchar not null,
    scope_id varchar not null,
    window_n integer not null,
    parent_window_n integer,
    raw_label varchar,
    normal_or_abnormal varchar,
    volume_level varchar,
    price_result_level varchar,
    efficiency_level varchar,
    bull_bear_score double,
    supply_score double,
    demand_score double,
    volatility_score double,
    description varchar,
    primary key (date, scope_type, scope_id, window_n)
);

create table if not exists vpa_sequence_stats (
    date varchar not null,
    scope_type varchar not null,
    scope_id varchar not null,
    window_n integer not null,
    parent_window_n integer,
    normal_count integer,
    abnormal_count integer,
    abnormal_ratio double,
    bullish_label_count integer,
    bearish_label_count integer,
    neutral_label_count integer,
    support_label_count integer,
    supply_label_count integer,
    high_volume_up_count integer,
    high_volume_down_count integer,
    high_volume_stall_count integer,
    long_upper_shadow_count integer,
    long_lower_shadow_count integer,
    low_volume_pullback_count integer,
    low_volume_rebound_count integer,
    breakout_like_count integer,
    breakdown_like_count integer,
    last_part_bull_score double,
    previous_part_bull_score double,
    bull_score_change double,
    sequence_pattern varchar,
    sequence_strength_score double,
    primary key (date, scope_type, scope_id, window_n)
);

create table if not exists vpa_structure_state (
    date varchar not null,
    scope_type varchar not null,
    scope_id varchar not null,
    state_10 varchar,
    state_20 varchar,
    state_30 varchar,
    state_60 varchar,
    state_120 varchar,
    state_240 varchar,
    final_state varchar,
    trend_background varchar,
    position_background varchar,
    market_score double,
    sector_score double,
    self_score double,
    relative_strength_score double,
    resonance_score double,
    final_rating varchar,
    confidence double,
    main_features varchar,
    risk_flags varchar,
    bullish_confirm_condition varchar,
    bearish_invalidate_condition varchar,
    primary key (date, scope_type, scope_id)
);
