create table if not exists ml_tradeability_daily (
    trade_date varchar not null,
    code varchar not null,
    industry_code varchar,
    industry_name varchar,
    is_st boolean,
    is_paused boolean,
    limit_up double,
    limit_down double,
    limit_up_pct double,
    limit_down_pct double,
    limit_band varchar,
    open double,
    high double,
    low double,
    close double,
    prev_close double,
    amount double,
    turnover_rate double,
    adv20_amount double,
    is_bse boolean,
    next_trade_date varchar,
    next_open double,
    next_limit_up double,
    next_limit_down double,
    next_is_paused boolean,
    can_buy_next_open boolean,
    can_sell_next_open boolean,
    generated_at varchar,
    primary key (trade_date, code)
);

create table if not exists ml_feature_mart_daily (
    trade_date varchar not null,
    code varchar not null,
    feature_set_id varchar not null,
    vpa_data_version varchar,
    generated_at varchar not null,
    industry_code varchar,
    industry_name varchar,
    is_st boolean,
    is_paused boolean,
    limit_up double,
    limit_down double,
    limit_up_pct double,
    limit_down_pct double,
    limit_band varchar,
    adv20_amount double,
    can_buy_next_open boolean,
    can_sell_next_open boolean,
    is_bse boolean,
    features_json varchar,
    primary key (trade_date, code, feature_set_id)
);

create table if not exists ml_labels_daily (
    trade_date varchar not null,
    code varchar not null,
    horizon_d integer not null,
    label_base varchar not null,
    limit_up_pct double,
    limit_down_pct double,
    limit_band varchar,
    base_price double,
    future_ret double,
    future_max_gain double,
    future_max_drawdown double,
    future_score double,
    future_rank_pct double,
    rank_label integer,
    absolute_ret double,
    absolute_rank_pct double,
    absolute_label integer,
    market_ret double,
    industry_ret double,
    market_excess_ret double,
    industry_excess_ret double,
    active_score double,
    active_rank_pct double,
    active_label integer,
    benchmark_missing_market boolean,
    benchmark_missing_industry boolean,
    benchmark_peer_count integer,
    risk_label integer,
    outperform_market boolean,
    generated_at varchar not null,
    primary key (trade_date, code, horizon_d, label_base)
);

create table if not exists ml_market_benchmark_daily (
    trade_date varchar not null,
    horizon_d integer not null,
    label_base varchar not null,
    market_ret double,
    benchmark_peer_count integer,
    generated_at varchar,
    primary key (trade_date, horizon_d, label_base)
);

create table if not exists ml_industry_benchmark_daily (
    trade_date varchar not null,
    industry_code varchar not null,
    horizon_d integer not null,
    label_base varchar not null,
    industry_ret double,
    benchmark_peer_count integer,
    generated_at varchar,
    primary key (trade_date, industry_code, horizon_d, label_base)
);

create table if not exists ml_model_registry (
    model_id varchar not null,
    model_type varchar not null,
    feature_set_id varchar not null,
    label_name varchar not null,
    label_base varchar not null,
    horizon_d integer not null,
    run_id varchar,
    fold_id varchar,
    feature_store_version varchar,
    feature_schema_hash varchar,
    train_start varchar,
    train_end varchar,
    valid_start varchar,
    valid_end varchar,
    test_start varchar,
    test_end varchar,
    params_json varchar,
    metrics_json varchar,
    feature_schema_uri varchar,
    artifact_uri varchar not null,
    is_active boolean,
    activated_at varchar,
    deactivated_at varchar,
    created_at varchar not null,
    notes varchar,
    primary key (model_id)
);

create table if not exists ml_runs (
    run_id varchar primary key,
    run_type varchar not null,
    experiment_name varchar,
    config_path varchar,
    config_hash varchar,
    git_commit varchar,
    alpha_data_db varchar,
    alpha_data_latest_date varchar,
    vpa_db varchar,
    ml_db varchar,
    feature_set_id varchar,
    feature_store_version varchar,
    label_version varchar,
    score_version varchar,
    artifact_root varchar,
    created_at varchar,
    started_at varchar,
    finished_at varchar,
    status varchar,
    notes varchar
);

create table if not exists ml_run_folds (
    run_id varchar not null,
    fold_id varchar not null,
    train_start varchar,
    train_end varchar,
    valid_start varchar,
    valid_end varchar,
    test_start varchar,
    test_end varchar,
    gap_type varchar,
    embargo_days integer,
    status varchar,
    artifact_dir varchar,
    created_at varchar,
    primary key (run_id, fold_id)
);

create table if not exists ml_model_bundles (
    bundle_id varchar primary key,
    run_id varchar not null,
    fold_id varchar,
    bundle_role varchar,
    absolute_model_id varchar,
    active_model_id varchar,
    risk_model_id varchar,
    feature_set_id varchar,
    label_base varchar,
    horizon_d integer,
    score_version varchar,
    artifact_dir varchar,
    status varchar,
    created_at varchar,
    activated_at varchar,
    deactivated_at varchar,
    notes varchar
);

create table if not exists ml_market_regime_daily (
    trade_date varchar primary key,
    trend_score double,
    breadth_score double,
    sentiment_score double,
    liquidity_score double,
    volatility_score double,
    final_regime varchar,
    generated_at varchar
);

create table if not exists ml_model_health_daily (
    trade_date varchar not null,
    model_or_bundle_id varchar not null,
    strategy_id varchar,
    score_version varchar,
    rolling_20d_return double,
    rolling_60d_return double,
    rolling_20d_drawdown double,
    rolling_60d_drawdown double,
    equity_above_ma60 boolean,
    enabled_by_health boolean,
    reason varchar,
    primary key (trade_date, model_or_bundle_id, strategy_id, score_version)
);

create table if not exists ml_strategy_allocation_daily (
    trade_date varchar not null,
    strategy_id varchar not null,
    sleeve varchar not null,
    bundle_id varchar,
    score_version varchar,
    raw_weight double,
    regime_multiplier double,
    health_multiplier double,
    drawdown_multiplier double,
    final_weight double,
    reason varchar,
    generated_at varchar,
    primary key (trade_date, strategy_id, sleeve, bundle_id, score_version)
);

create table if not exists live_target_positions (
    trade_date varchar not null,
    account_id varchar not null,
    strategy_id varchar not null,
    code varchar not null,
    target_weight double,
    target_value double,
    source_bundle_id varchar,
    source_sleeve varchar,
    score_version varchar,
    reason varchar,
    generated_at varchar,
    primary key (trade_date, account_id, strategy_id, code)
);

create table if not exists live_orders (
    order_id varchar primary key,
    trade_date varchar not null,
    account_id varchar not null,
    strategy_id varchar not null,
    code varchar not null,
    side varchar not null,
    order_qty double,
    order_price double,
    status varchar,
    block_reason varchar,
    created_at varchar,
    submitted_at varchar,
    updated_at varchar
);

create table if not exists live_fills (
    fill_id varchar primary key,
    order_id varchar,
    trade_date varchar,
    code varchar,
    side varchar,
    fill_qty double,
    fill_price double,
    fill_time varchar,
    commission double,
    tax double,
    slippage_bps double
);

create table if not exists live_risk_logs (
    trade_date varchar,
    account_id varchar,
    strategy_id varchar,
    check_name varchar,
    severity varchar,
    passed boolean,
    action varchar,
    reason varchar,
    created_at varchar
);

create table if not exists ml_predictions_daily (
    trade_date varchar not null,
    code varchar not null,
    model_id varchar not null,
    horizon_d integer not null,
    alpha_score double,
    alpha_rank_pct double,
    absolute_score double,
    absolute_rank_pct double,
    absolute_zscore double,
    reg_score double,
    active_score double,
    active_rank_pct double,
    active_zscore double,
    risk_score double,
    risk_prob double,
    risk_rank_pct double,
    risk_zscore double,
    context_score double,
    liquidity_score double,
    relative_strength_pct double,
    resonance_pct double,
    penalty_score double,
    core_score double,
    trade_score double,
    trade_score_v2 double,
    score_version varchar,
    run_id varchar,
    fold_id varchar,
    absolute_model_id varchar,
    active_model_id varchar,
    risk_model_id varchar,
    feature_set_id varchar not null,
    generated_at varchar not null,
    primary key (trade_date, code, model_id, horizon_d)
);

create table if not exists ml_prediction_raw_daily (
    trade_date varchar not null,
    code varchar not null,
    run_id varchar not null,
    fold_id varchar not null,
    score_version varchar not null,
    feature_set_id varchar not null,
    horizon_d integer not null,
    absolute_model_id varchar,
    active_model_id varchar,
    risk_model_id varchar,
    absolute_score double,
    active_score double,
    risk_prob double,
    generated_at varchar not null,
    primary key (trade_date, code, run_id, fold_id, horizon_d)
);

create table if not exists ml_portfolio_targets_daily (
    run_id varchar,
    fold_id varchar,
    trade_date varchar not null,
    portfolio_id varchar not null,
    score_version varchar,
    code varchar not null,
    target_weight double,
    rank_n integer,
    trade_score double,
    entry_reason varchar,
    signal_action varchar,
    hold_reason varchar,
    exit_reason varchar,
    sell_blocked_reason varchar,
    entry_date varchar,
    entry_price double,
    shares double,
    holding_days integer,
    entry_trade_score double,
    latest_trade_score double,
    generated_at varchar,
    primary key (trade_date, run_id, fold_id, portfolio_id, score_version, code)
);

create table if not exists ml_portfolio_construction_diagnostics (
    trade_date varchar not null,
    run_id varchar not null,
    fold_id varchar not null,
    portfolio_id varchar not null,
    score_version varchar not null,
    raw_candidate_count integer,
    hard_filter_pass_count integer,
    core_pool_size integer,
    candidate_pool_size integer,
    selected_from_core integer,
    selected_from_candidate integer,
    final_selected_count integer,
    low_adv_rejected_count integer,
    cannot_buy_rejected_count integer,
    st_rejected_count integer,
    paused_rejected_count integer,
    bse_rejected_count integer,
    low_trade_score_rejected_count integer,
    high_risk_rejected_count integer,
    industry_limit_blocked_count integer,
    unknown_industry_limit_blocked_count integer,
    max_new_entries_blocked_count integer,
    retained_holdings_count integer,
    sell_signal_count integer,
    sell_executed_count integer,
    sell_blocked_count integer,
    hold_due_to_min_days_count integer,
    hold_due_to_score_ok_count integer,
    exit_due_to_score_count integer,
    exit_due_to_risk_count integer,
    exit_due_to_time_count integer,
    exit_due_to_not_candidate_count integer,
    avg_holding_days_current double,
    median_holding_days_current double,
    cash_weight double,
    created_at varchar,
    primary key (trade_date, run_id, fold_id, portfolio_id, score_version)
);

create table if not exists ml_backtest_orders (
    run_id varchar,
    fold_id varchar,
    strategy_id varchar,
    score_version varchar,
    sim_date varchar not null,
    decision_date varchar not null,
    code varchar not null,
    side varchar not null,
    order_seq integer,
    qty double,
    target_weight double,
    order_px_ref varchar,
    fill_px double,
    status varchar not null,
    reason varchar,
    entry_date varchar,
    entry_price double,
    exit_date varchar,
    holding_days integer,
    entry_trade_score double,
    exit_trade_score double,
    entry_abs_rank_pct double,
    entry_risk_rank_pct double,
    entry_reason varchar,
    exit_reason varchar,
    sell_blocked_reason varchar,
    realized_pnl double
);

create table if not exists ml_backtest_positions (
    run_id varchar,
    fold_id varchar,
    strategy_id varchar,
    score_version varchar,
    sim_date varchar not null,
    code varchar not null,
    position_qty double,
    market_value double,
    weight double,
    entry_date varchar,
    entry_price double,
    holding_days integer,
    entry_trade_score double,
    entry_reason varchar
);

create table if not exists ml_backtest_nav (
    run_id varchar,
    fold_id varchar,
    strategy_id varchar,
    score_version varchar,
    sim_date varchar not null,
    nav double not null,
    cash double not null,
    gross_exposure double not null,
    turnover double not null
);

create table if not exists ml_backtest_metrics (
    run_id varchar not null,
    fold_id varchar,
    strategy_id varchar,
    score_version varchar,
    start_date varchar,
    end_date varchar,
    metric_name varchar not null,
    metric_value double,
    annual_return double,
    total_return double,
    max_drawdown double,
    calmar_like double,
    turnover double,
    win_rate double,
    empty_day_ratio double,
    cash_ratio_avg double,
    bse_excluded_count double,
    unknown_industry_weight_avg double,
    core_pool_size_avg double,
    candidate_pool_size_avg double,
    avg_holding_days double,
    median_holding_days double,
    max_holding_days double,
    holding_segment_count double,
    turnover_daily_avg double,
    sell_blocked_count double,
    segment varchar not null,
    primary key (run_id, fold_id, score_version, metric_name, segment)
);
